# Copyright 2026 MajestaNet
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# SPDX-License-Identifier: Apache-2.0

"""Load ``$TWO_DATA_DIR/env`` without overriding process environment.

No network. Process environment still wins (ADR 0013 P7).
"""

from __future__ import annotations

import json
import os
import sys
from collections.abc import Mapping, MutableMapping
from pathlib import Path
from urllib.parse import urlparse

from two.runtime.env import is_public_bind_host
from two.setup import (
    DEFAULT_API_BIND,
    DEFAULT_API_PORT,
    DEFAULT_OLLAMA_PORT,
    DEFAULT_PROFILE,
    DEFAULT_TOPOLOGY,
    DUMMY_OLLAMA_KEY,
    PublicOllamaHostError,
    refuse_public_ollama_host,
)

ENV_FILE_NAME = "env"
ENV_DATA_DIR = "TWO_DATA_DIR"
ENV_WORKSPACE_ROOT = "TWO_WORKSPACE_ROOT"
ENV_API_BIND = "TWO_API_BIND"
ENV_MAC_URL = "MAC_QWEN_BASE_URL"


class PublicOllamaUrlError(PublicOllamaHostError):
    """Ollama base URL would use a public bind."""


def default_data_dir(
    *,
    home: Path | None = None,
    system: str | None = None,
) -> Path:
    """Platform default for interactive ``TWO_DATA_DIR`` (ADR 0013 P1)."""

    base = home if home is not None else Path.home()
    plat = system if system is not None else sys.platform
    if plat == "darwin":
        return base / "Library" / "Application Support" / "two"
    return base / ".local" / "share" / "two"


def default_workspace_root(data_dir: Path) -> Path:
    return data_dir / "worktrees"


def env_file_path(data_dir: Path) -> Path:
    return data_dir / ENV_FILE_NAME


def parse_env_file(path: Path) -> dict[str, str]:
    """Parse KEY=VALUE lines. Comments and blank lines are ignored."""

    parsed: dict[str, str] = {}
    for raw in path.read_text(encoding="utf-8").splitlines():
        stripped = raw.strip()
        if not stripped or stripped.startswith("#"):
            continue
        if stripped.startswith("export "):
            stripped = stripped[len("export ") :].strip()
        if "=" not in stripped:
            continue
        key, value = stripped.split("=", 1)
        parsed[key.strip()] = _unquote(value.strip())
    return parsed


def format_env_value(value: str) -> str:
    if any(ch.isspace() or ch in "#'\"" for ch in value):
        return json.dumps(value)
    return value


def canonical_ollama_url(url: str) -> str:
    """Return ``http://host:port/v1`` or raise if the host is a public bind."""

    cleaned = url.strip()
    parsed = urlparse(cleaned)
    host = parsed.hostname
    if host is None:
        host = refuse_public_ollama_host(cleaned)
        port = DEFAULT_OLLAMA_PORT
    else:
        if is_public_bind_host(host):
            raise PublicOllamaUrlError(
                f"refusing public Ollama URL {url!r}; use a private LAN or overlay name"
            )
        refuse_public_ollama_host(host)
        port = parsed.port or DEFAULT_OLLAMA_PORT
    return f"http://{host}:{port}/v1"


def render_env_file(
    *,
    data_dir: Path,
    workspace_root: Path,
    ollama_url: str,
    topology: str = DEFAULT_TOPOLOGY,
    profile: str = DEFAULT_PROFILE,
    api_bind: str = DEFAULT_API_BIND,
    api_port: int = DEFAULT_API_PORT,
) -> str:
    url = canonical_ollama_url(ollama_url)
    rows = {
        "TWO_TOPOLOGY": topology,
        "TWO_INFERENCE_PROFILE": profile,
        "TWO_DATA_DIR": str(data_dir),
        "TWO_WORKSPACE_ROOT": str(workspace_root),
        "TWO_API_BIND": api_bind,
        "TWO_API_PORT": str(api_port),
        "MAC_QWEN_BASE_URL": url,
        "MAC_QWEN_API_KEY": DUMMY_OLLAMA_KEY,
    }
    lines = ["# Generated by two setup. No secrets."]
    for key, value in rows.items():
        lines.append(f"{key}={format_env_value(value)}")
    return "\n".join(lines) + "\n"


def candidate_data_dirs(
    *,
    environ: Mapping[str, str] | None = None,
    home: Path | None = None,
    cwd: Path | None = None,
    system: str | None = None,
) -> list[Path]:
    env = environ if environ is not None else os.environ
    configured = env.get(ENV_DATA_DIR, "").strip()
    if configured:
        return [Path(configured)]
    base = home if home is not None else Path.home()
    here = cwd if cwd is not None else Path.cwd()
    ordered = [
        default_data_dir(home=base, system=system),
        base / ".local" / "share" / "two",
        here / "var" / "two",
    ]
    unique: list[Path] = []
    seen: set[Path] = set()
    for path in ordered:
        resolved = path
        if resolved in seen:
            continue
        seen.add(resolved)
        unique.append(resolved)
    return unique


def discover_env_file(
    *,
    environ: Mapping[str, str] | None = None,
    home: Path | None = None,
    cwd: Path | None = None,
    system: str | None = None,
) -> Path | None:
    for data_dir in candidate_data_dirs(environ=environ, home=home, cwd=cwd, system=system):
        path = env_file_path(data_dir)
        if path.is_file():
            return path
    return None


def load_data_dir_env(
    environ: MutableMapping[str, str] | None = None,
    *,
    home: Path | None = None,
    cwd: Path | None = None,
    system: str | None = None,
) -> Path | None:
    """Fill missing keys from ``$TWO_DATA_DIR/env``. Existing keys win."""

    env: MutableMapping[str, str]
    env = environ if environ is not None else os.environ
    path = discover_env_file(environ=env, home=home, cwd=cwd, system=system)
    if path is None:
        return None
    parsed = parse_env_file(path)
    for key, value in parsed.items():
        if not str(env.get(key, "")).strip():
            env[key] = value
    return path


def _unquote(value: str) -> str:
    if len(value) >= 2 and value[0] == value[-1] and value[0] in {'"', "'"}:
        inner = value[1:-1]
        if value[0] == '"':
            try:
                loaded = json.loads(value)
            except json.JSONDecodeError:
                return inner
            if isinstance(loaded, str):
                return loaded
        return inner
    return value
