#!/usr/bin/env bash
# Copyright 2026 MajestaNet
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

DRY_RUN=0
TOPOLOGY="${TWO_TOPOLOGY:-split}"
DATA_DIR="${TWO_DATA_DIR:-}"
WORKSPACE_ROOT="${TWO_WORKSPACE_ROOT:-}"
OLLAMA_URL="${MAC_QWEN_BASE_URL:-}"
SYSTEMD=0

usage() {
  cat <<'EOF'
Usage: bootstrap-dev-host.sh [--dry-run] [--topology split|colocated]
                             [--data-dir DIR] [--workspace-root DIR]
                             [--ollama-url URL] [--systemd]

Idempotent Linux development-host bootstrap (architecture §12.2 / §12.5).

  --dry-run          Print the plan and exit 0 (CI path; no systemd, no Docker)
  --topology         split (default, Mac over LAN/overlay) or colocated (127.0.0.1)
  --data-dir         TWO_DATA_DIR (default: $HOME/.local/share/two)
  --workspace-root   TWO_WORKSPACE_ROOT (default: $DATA_DIR/worktrees)
  --ollama-url       MAC_QWEN_BASE_URL; colocated forces http://127.0.0.1:11434/v1
  --systemd          Copy unit templates to ~/.config/systemd/user (live only)

Compose is the default unattended packaging (ADR 0005):
  cd deploy/compose && docker compose up -d api scheduler worker
systemd user units under deploy/systemd/ are optional native templates.

Closing a CLI does not require stopping Compose.
Permissions: TWO_DATA_DIR and the workspace root are created mode 0700.
Never bind the API or Ollama to 0.0.0.0. Do not Dockerize Ollama.
EOF
}

refuse_public() {
  local value="$1"
  case "$value" in
    *0.0.0.0*|*'[::]'*|*'::'*|*'://*' )
      if [[ "$value" == *0.0.0.0* || "$value" == *'[::]'* ]]; then
        echo "bootstrap-dev-host.sh: refusing public bind $value" >&2
        return 1
      fi
      ;;
  esac
  return 0
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --dry-run)
      DRY_RUN=1
      shift
      ;;
    --topology)
      TOPOLOGY="${2:?--topology requires split or colocated}"
      shift 2
      ;;
    --data-dir)
      DATA_DIR="${2:?--data-dir requires a path}"
      shift 2
      ;;
    --workspace-root)
      WORKSPACE_ROOT="${2:?--workspace-root requires a path}"
      shift 2
      ;;
    --ollama-url)
      OLLAMA_URL="${2:?--ollama-url requires a URL}"
      shift 2
      ;;
    --systemd)
      SYSTEMD=1
      shift
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "bootstrap-dev-host.sh: unknown argument: $1" >&2
      usage >&2
      exit 1
      ;;
  esac
done

case "$TOPOLOGY" in
  split|colocated) ;;
  *)
    echo "bootstrap-dev-host.sh: topology must be split or colocated, got $TOPOLOGY" >&2
    exit 1
    ;;
esac

if [[ -z "$DATA_DIR" ]]; then
  DATA_DIR="${HOME}/.local/share/two"
fi
if [[ -z "$WORKSPACE_ROOT" ]]; then
  WORKSPACE_ROOT="${DATA_DIR}/worktrees"
fi

if [[ "$TOPOLOGY" == "colocated" ]]; then
  OLLAMA_URL="http://127.0.0.1:11434/v1"
elif [[ -z "$OLLAMA_URL" ]]; then
  OLLAMA_URL="http://mac-inference.internal:11434/v1"
fi

if ! refuse_public "$OLLAMA_URL"; then
  exit 1
fi
if ! refuse_public "$DATA_DIR"; then
  exit 1
fi

UNITS_SRC="${ROOT}/deploy/systemd"
COMPOSE_DIR="${ROOT}/deploy/compose"
ENV_FILE="${DATA_DIR}/env"
UNITS_DEST="${HOME}/.config/systemd/user"

print_plan() {
  cat <<EOF
Majesta Two development-host bootstrap (architecture §12.2 / §12.5)
topology: ${TOPOLOGY}
TWO_DATA_DIR=${DATA_DIR} (mode 0700)
TWO_WORKSPACE_ROOT=${WORKSPACE_ROOT} (mode 0700)
MAC_QWEN_BASE_URL=${OLLAMA_URL}
TWO_API_BIND=127.0.0.1
TWO_API_PORT=8741
env_file: ${ENV_FILE} (mode 0600)

# Default unattended packaging: Compose (ADR 0005)
#   cd ${COMPOSE_DIR}
#   docker compose up -d api scheduler worker
#   docker compose run --rm two --help
# Services: api, scheduler, worker (optional slack profile is a stub)
# No Ollama image. No public 11434/8741. Host network; API on 127.0.0.1.

# Optional native systemd user units (templates, not installed in --dry-run)
#   ${UNITS_SRC}/two-api.service
#   ${UNITS_SRC}/two-scheduler.service
#   ${UNITS_SRC}/two-worker.service
#   ${UNITS_SRC}/two.target
# Live --systemd copies them to ${UNITS_DEST}

# Health from this Linux host (not from a public bind):
#   ./scripts/health-check.sh --dry-run
#   MAC_QWEN_BASE_URL=${OLLAMA_URL} ./scripts/health-check.sh
# API process health: GET http://127.0.0.1:8741/health
# Scheduler Mac poller uses MAC_QWEN_BASE_URL when set (else Healthy/offline).

# Closing a CLI does not require stopping Compose.
# Do not bind the API or Ollama on a public interface. Do not Dockerize Ollama.
EOF
}

print_plan

if [[ "$DRY_RUN" -eq 1 ]]; then
  exit 0
fi

umask 077
mkdir -p "$DATA_DIR" "$WORKSPACE_ROOT"
chmod 700 "$DATA_DIR" "$WORKSPACE_ROOT"

cat > "$ENV_FILE" <<EOF
# Generated by bootstrap-dev-host.sh. No secrets.
TWO_TOPOLOGY=${TOPOLOGY}
TWO_DATA_DIR=${DATA_DIR}
TWO_WORKSPACE_ROOT=${WORKSPACE_ROOT}
TWO_API_BIND=127.0.0.1
TWO_API_PORT=8741
MAC_QWEN_BASE_URL=${OLLAMA_URL}
TWO_INFERENCE_PROFILE=${TWO_INFERENCE_PROFILE:-m24-qwen38-16k}
EOF
chmod 600 "$ENV_FILE"
echo "+ wrote ${ENV_FILE}"

if [[ "$SYSTEMD" -eq 1 ]]; then
  mkdir -p "$UNITS_DEST"
  for unit in two-api.service two-scheduler.service two-worker.service two.target; do
    src="${UNITS_SRC}/${unit}"
    dest="${UNITS_DEST}/${unit}"
    cp "$src" "$dest"
    echo "+ copied ${dest}"
  done
  echo "+ enable with: systemctl --user daemon-reload && systemctl --user enable --now two.target"
  echo "+ Compose remains the default; systemd is optional."
fi

echo "bootstrap-dev-host.sh: ready topology=${TOPOLOGY} data=${DATA_DIR}"
echo "Next: cd deploy/compose && docker compose up -d api scheduler worker"
